### ISSUE TITLE
Issues running my own instance

### ISSUE THREAD

**Issue by SasLuca** [covidpass-org/docker-compose#1]
Hi, I tried running my own instance of the app but ran into several issues:

1. While I managed to generate all the apple certificates and place them accordingly based on my reading on the docker-compose file, there is no explanation of what apple-developer-password is and how I should set that up.

2. What other things do I need to customize in order to run my own instance besides placing my own certificates? 

Thanks

**Comment by idominiki** [comment]
@SasLuca How do you managed this?

**Comment by SasLuca** [comment]
Well, I just didnt use the docker-compose file. I ran the backend directly and hardcoded my password in the code. 
I got how the backend works but I had some other issues with docker-compose in the end.
